# Generated by Django 5.2.5 on 2025-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('release_date', models.DateField()),
                ('episodes', models.ManyToManyField(related_name='stories', to='stories.episode')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
