# Generated by Django 5.2.5 on 2025-08-24 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stories', '0003_category_story_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('username', models.CharField(help_text='Reader name (2-50 characters)', max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('comment', models.TextField(help_text='Comment content (minimum 5 characters)', validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(blank=True, help_text='Optional email for notifications', max_length=254)),
                ('is_approved', models.BooleanField(default=True, help_text='Approve/moderate comments')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature exceptional comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='stories_com_content_5df554_idx'), models.Index(fields=['created_at'], name='stories_com_created_615d52_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reaction_type', models.CharField(choices=[('heart', '❤️ Heart'), ('like', '👍 Like'), ('love', '😍 Love'), ('laugh', '😂 Laugh'), ('wow', '😮 Wow')], default='heart', max_length=10)),
                ('username', models.CharField(blank=True, help_text='Optional username for reaction', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address for duplicate prevention')),
                ('user_agent', models.TextField(blank=True, help_text='Browser info for duplicate prevention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='stories_rea_content_6025f3_idx'), models.Index(fields=['reaction_type'], name='stories_rea_reactio_32490e_idx')],
                'unique_together': {('content_type', 'object_id', 'ip_address', 'reaction_type')},
            },
        ),
    ]
