# Generated by Django 5.2.5 on 2025-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or emoji for genre', max_length=50),
        ),
    ]
