# Generated by Django 5.2.5 on 2025-08-28 20:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_genre_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_dv', models.CharField(help_text='Title in Dhivehi', max_length=200)),
                ('title_en', models.CharField(help_text='Title in English', max_length=200)),
                ('content_dv', models.TextField(help_text='Story content in Dhivehi')),
                ('content_en', models.TextField(help_text='Story content in English')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this story on homepage')),
                ('is_published', models.BooleanField(default=True, help_text='Published status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_stories', to='stories.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_stories', to='stories.category')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.genre')),
            ],
            options={
                'verbose_name': 'Short Story',
                'verbose_name_plural': 'Short Stories',
                'ordering': ['-published_date', '-created_at'],
                'indexes': [models.Index(fields=['published_date'], name='stories_sho_publish_63978c_idx'), models.Index(fields=['is_published', 'is_featured'], name='stories_sho_is_publ_915835_idx')],
            },
        ),
    ]
