# Generated by Django 5.2.5 on 2025-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_author_profile_image_alter_story_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this story on homepage'),
        ),
    ]
