# Generated by Django 5.2.5 on 2025-08-31 16:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_story_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Character description and background')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Character image', max_length=255, null=True, verbose_name='image')),
                ('is_main_character', models.BooleanField(default=False, help_text='Is this a main character?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(help_text='Story this character belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.story')),
            ],
            options={
                'ordering': ['-is_main_character', 'name'],
                'unique_together': {('story', 'name')},
            },
        ),
    ]
