# Generated by Django 5.2.5 on 2025-09-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_character'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, help_text='Character description (optional if shown in image)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, help_text='Character name (optional if shown in image)', max_length=100),
        ),
    ]
