# Generated by Django 5.2.5 on 2025-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_make_character_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description_dv',
            field=models.TextField(blank=True, help_text='Description in Dhivehi'),
        ),
        migrations.AddField(
            model_name='story',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English'),
        ),
        migrations.AddField(
            model_name='story',
            name='title_dv',
            field=models.CharField(blank=True, help_text='Title in Dhivehi', max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title in English', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
