# Generated by Django 5.2.5 on 2025-09-01 16:42

from django.db import migrations
import re


def detect_language_and_populate(apps, schema_editor):
    """
    Detect if existing content is in Dhivehi or English and populate appropriate fields.
    """
    Story = apps.get_model('stories', 'Story')
    
    # Dhivehi Unicode range (approximately)
    dhivehi_pattern = re.compile(r'[\u0780-\u07BF]+')
    
    for story in Story.objects.all():
        # Check title
        if story.title:
            if dhivehi_pattern.search(story.title):
                # Contains Dhivehi characters
                story.title_dv = story.title
            else:
                # Assume English if no Dhivehi characters
                story.title_en = story.title
        
        # Check description
        if story.description:
            if dhivehi_pattern.search(story.description):
                # Contains Dhivehi characters
                story.description_dv = story.description
            else:
                # Assume English if no Dhivehi characters
                story.description_en = story.description
        
        story.save()


def reverse_populate(apps, schema_editor):
    """
    Reverse the data migration - not really needed as we're keeping legacy fields.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_description_dv_story_description_en_and_more'),
    ]

    operations = [
        migrations.RunPython(detect_language_and_populate, reverse_populate),
    ]
